version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/log/error.log:/var/log/nginx/error.log
      - ./.docker/nginx/log/access.log:/var/log/nginx/access.log
    depends_on:
      - php
    restart: always

  php:
    image: php:8-fpm
    volumes:
      - ./:/var/www/html
    restart: always
